// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkg/agent.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_SHADOWSOCKS NodeType = 0
	NodeType_TROJAN      NodeType = 1
	NodeType_VMESS       NodeType = 2
	NodeType_HYSTERIA    NodeType = 3
	NodeType_HYSTERIA2   NodeType = 4
	NodeType_ANYTLS      NodeType = 6
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "SHADOWSOCKS",
		1: "TROJAN",
		2: "VMESS",
		3: "HYSTERIA",
		4: "HYSTERIA2",
		6: "ANYTLS",
	}
	NodeType_value = map[string]int32{
		"SHADOWSOCKS": 0,
		"TROJAN":      1,
		"VMESS":       2,
		"HYSTERIA":    3,
		"HYSTERIA2":   4,
		"ANYTLS":      6,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_pkg_agent_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{0}
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_pkg_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ConfigRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	RawData       []byte                 `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pkg_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ConfigResponse) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Port          string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

func (x *RegisterRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RegisterRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegisterId    string                 `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	RegisterId    string                 `protobuf:"bytes,2,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_pkg_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

func (x *UnregisterRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

type UnregisterResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResult) Reset() {
	*x = UnregisterResult{}
	mi := &file_pkg_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResult) ProtoMessage() {}

func (x *UnregisterResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResult.ProtoReflect.Descriptor instead.
func (*UnregisterResult) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterResult) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	RegisterId    string                 `protobuf:"bytes,2,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

func (x *HeartbeatRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	RegisterId    string                 `protobuf:"bytes,2,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	RawData       []byte                 `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	RawStats      []byte                 `protobuf:"bytes,4,opt,name=raw_stats,json=rawStats,proto3" json:"raw_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_pkg_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

func (x *SubmitRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

func (x *SubmitRequest) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *SubmitRequest) GetRawStats() []byte {
	if x != nil {
		return x.RawStats
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_pkg_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type UsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	RegisterId    string                 `protobuf:"bytes,2,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersRequest) Reset() {
	*x = UsersRequest{}
	mi := &file_pkg_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersRequest) ProtoMessage() {}

func (x *UsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersRequest.ProtoReflect.Descriptor instead.
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UsersRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

func (x *UsersRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_pkg_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UsersResponse) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=pkg.NodeType" json:"node_type,omitempty"`
	RegisterId    string                 `protobuf:"bytes,2,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_pkg_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_SHADOWSOCKS
}

func (x *VerifyRequest) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_pkg_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_pkg_agent_proto protoreflect.FileDescriptor

const file_pkg_agent_proto_rawDesc = "" +
	"\n" +
	"\x0fpkg/agent.proto\x12\x03pkg\"T\n" +
	"\rConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12*\n" +
	"\tnode_type\x18\x02 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\"C\n" +
	"\x0eConfigResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x19\n" +
	"\braw_data\x18\x02 \x01(\fR\arawData\"\x97\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12*\n" +
	"\tnode_type\x18\x02 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\"3\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vregister_id\x18\x01 \x01(\tR\n" +
	"registerId\"`\n" +
	"\x11UnregisterRequest\x12*\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\x12\x1f\n" +
	"\vregister_id\x18\x02 \x01(\tR\n" +
	"registerId\"*\n" +
	"\x10UnregisterResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"_\n" +
	"\x10HeartbeatRequest\x12*\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\x12\x1f\n" +
	"\vregister_id\x18\x02 \x01(\tR\n" +
	"registerId\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\x94\x01\n" +
	"\rSubmitRequest\x12*\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\x12\x1f\n" +
	"\vregister_id\x18\x02 \x01(\tR\n" +
	"registerId\x12\x19\n" +
	"\braw_data\x18\x03 \x01(\fR\arawData\x12\x1b\n" +
	"\traw_stats\x18\x04 \x01(\fR\brawStats\"(\n" +
	"\x0eSubmitResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"[\n" +
	"\fUsersRequest\x12*\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\x12\x1f\n" +
	"\vregister_id\x18\x02 \x01(\tR\n" +
	"registerId\"*\n" +
	"\rUsersResponse\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\"\\\n" +
	"\rVerifyRequest\x12*\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\r.pkg.NodeTypeR\bnodeType\x12\x1f\n" +
	"\vregister_id\x18\x02 \x01(\tR\n" +
	"registerId\"(\n" +
	"\x0eVerifyResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result*[\n" +
	"\bNodeType\x12\x0f\n" +
	"\vSHADOWSOCKS\x10\x00\x12\n" +
	"\n" +
	"\x06TROJAN\x10\x01\x12\t\n" +
	"\x05VMESS\x10\x02\x12\f\n" +
	"\bHYSTERIA\x10\x03\x12\r\n" +
	"\tHYSTERIA2\x10\x04\x12\n" +
	"\n" +
	"\x06ANYTLS\x10\x062\x82\x03\n" +
	"\x05Agent\x121\n" +
	"\x06Config\x12\x12.pkg.ConfigRequest\x1a\x13.pkg.ConfigResponse\x12:\n" +
	"\tHeartbeat\x12\x15.pkg.HeartbeatRequest\x1a\x16.pkg.HeartbeatResponse\x121\n" +
	"\x06Submit\x12\x12.pkg.SubmitRequest\x1a\x13.pkg.SubmitResponse\x12.\n" +
	"\x05Users\x12\x11.pkg.UsersRequest\x1a\x12.pkg.UsersResponse\x127\n" +
	"\bRegister\x12\x14.pkg.RegisterRequest\x1a\x15.pkg.RegisterResponse\x12;\n" +
	"\n" +
	"Unregister\x12\x16.pkg.UnregisterRequest\x1a\x15.pkg.UnregisterResult\x121\n" +
	"\x06Verify\x12\x12.pkg.VerifyRequest\x1a\x13.pkg.VerifyResponseB0Z.github.com/xflash-panda/server-agent-proto/pkgb\x06proto3"

var (
	file_pkg_agent_proto_rawDescOnce sync.Once
	file_pkg_agent_proto_rawDescData []byte
)

func file_pkg_agent_proto_rawDescGZIP() []byte {
	file_pkg_agent_proto_rawDescOnce.Do(func() {
		file_pkg_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_proto_rawDesc), len(file_pkg_agent_proto_rawDesc)))
	})
	return file_pkg_agent_proto_rawDescData
}

var file_pkg_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_agent_proto_goTypes = []any{
	(NodeType)(0),             // 0: pkg.NodeType
	(*ConfigRequest)(nil),     // 1: pkg.ConfigRequest
	(*ConfigResponse)(nil),    // 2: pkg.ConfigResponse
	(*RegisterRequest)(nil),   // 3: pkg.RegisterRequest
	(*RegisterResponse)(nil),  // 4: pkg.RegisterResponse
	(*UnregisterRequest)(nil), // 5: pkg.UnregisterRequest
	(*UnregisterResult)(nil),  // 6: pkg.UnregisterResult
	(*HeartbeatRequest)(nil),  // 7: pkg.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 8: pkg.HeartbeatResponse
	(*SubmitRequest)(nil),     // 9: pkg.SubmitRequest
	(*SubmitResponse)(nil),    // 10: pkg.SubmitResponse
	(*UsersRequest)(nil),      // 11: pkg.UsersRequest
	(*UsersResponse)(nil),     // 12: pkg.UsersResponse
	(*VerifyRequest)(nil),     // 13: pkg.VerifyRequest
	(*VerifyResponse)(nil),    // 14: pkg.VerifyResponse
}
var file_pkg_agent_proto_depIdxs = []int32{
	0,  // 0: pkg.ConfigRequest.node_type:type_name -> pkg.NodeType
	0,  // 1: pkg.RegisterRequest.node_type:type_name -> pkg.NodeType
	0,  // 2: pkg.UnregisterRequest.node_type:type_name -> pkg.NodeType
	0,  // 3: pkg.HeartbeatRequest.node_type:type_name -> pkg.NodeType
	0,  // 4: pkg.SubmitRequest.node_type:type_name -> pkg.NodeType
	0,  // 5: pkg.UsersRequest.node_type:type_name -> pkg.NodeType
	0,  // 6: pkg.VerifyRequest.node_type:type_name -> pkg.NodeType
	1,  // 7: pkg.Agent.Config:input_type -> pkg.ConfigRequest
	7,  // 8: pkg.Agent.Heartbeat:input_type -> pkg.HeartbeatRequest
	9,  // 9: pkg.Agent.Submit:input_type -> pkg.SubmitRequest
	11, // 10: pkg.Agent.Users:input_type -> pkg.UsersRequest
	3,  // 11: pkg.Agent.Register:input_type -> pkg.RegisterRequest
	5,  // 12: pkg.Agent.Unregister:input_type -> pkg.UnregisterRequest
	13, // 13: pkg.Agent.Verify:input_type -> pkg.VerifyRequest
	2,  // 14: pkg.Agent.Config:output_type -> pkg.ConfigResponse
	8,  // 15: pkg.Agent.Heartbeat:output_type -> pkg.HeartbeatResponse
	10, // 16: pkg.Agent.Submit:output_type -> pkg.SubmitResponse
	12, // 17: pkg.Agent.Users:output_type -> pkg.UsersResponse
	4,  // 18: pkg.Agent.Register:output_type -> pkg.RegisterResponse
	6,  // 19: pkg.Agent.Unregister:output_type -> pkg.UnregisterResult
	14, // 20: pkg.Agent.Verify:output_type -> pkg.VerifyResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_agent_proto_init() }
func file_pkg_agent_proto_init() {
	if File_pkg_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_proto_rawDesc), len(file_pkg_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_proto_goTypes,
		DependencyIndexes: file_pkg_agent_proto_depIdxs,
		EnumInfos:         file_pkg_agent_proto_enumTypes,
		MessageInfos:      file_pkg_agent_proto_msgTypes,
	}.Build()
	File_pkg_agent_proto = out.File
	file_pkg_agent_proto_goTypes = nil
	file_pkg_agent_proto_depIdxs = nil
}
